grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 2
model_selection:
  module_0:
    class: AdaBoostClassifier
    module: sklearn.ensemble
    params:
      n_estimators : 50
      learning_rate : 1.0
    search_param_grid:
      n_estimators :
      -75
  module_1:
    class: RandomForestClassifier
    module: sklearn.ensemble
    params:
      min_samples_leaf: 3
    search_param_grid:
      min_samples_leaf:
      - 6

  module_2:
    class: GaussianNB
    module: sklearn.naive_bayes
    params:
     var_smoothing : 1e-09
    #search_param_grid:
      #min_samples_leaf:

  module_3:
    class: DecisionTreeClassifier 
    module: sklearn.tree
    params:
      min_samples_split : 2
      min_samples_leaf: 3
    search_param_grid:
      min_samples_leaf:
      - 6 